USE [master]
GO

/****** Object:  Database [DataWarehouse]    Script Date: 26/06/2025 4:16:54 pm ******/
CREATE DATABASE [DataWarehouse]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataWarehouse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataWarehouse] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataWarehouse] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataWarehouse] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataWarehouse] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataWarehouse] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataWarehouse] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DataWarehouse] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataWarehouse] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataWarehouse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataWarehouse] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataWarehouse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataWarehouse] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataWarehouse] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataWarehouse] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataWarehouse] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DataWarehouse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataWarehouse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataWarehouse] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataWarehouse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataWarehouse] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataWarehouse] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataWarehouse] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataWarehouse] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataWarehouse] SET  MULTI_USER 
GO

ALTER DATABASE [DataWarehouse] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataWarehouse] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataWarehouse] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataWarehouse] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DataWarehouse] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataWarehouse] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DataWarehouse] SET QUERY_STORE = ON
GO

ALTER DATABASE [DataWarehouse] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DataWarehouse] SET  READ_WRITE 
GO


